language: cpp

os:
  - linux

compiler:
  - clang

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y bash coreutils g++-4.8 g++-4.9 clang-3.4

before_script:
  - echo $LANG
  - echo $LC_ALL
  - lsb_release -a
  - uname -a
  - apt-cache search '^g\+\+|^clang'
  - for cc in g++-4.8 g++-4.9 clang++-3.4 clang++-3.5; do which $cc || echo "no $cc installed"; done
  - g++ --version
  - clang++ --version

script:
  - NO_CLEAR=true ./validate.sh

branches:
  only:
    - dev

notifications:
  email:
    on_success: change
    on_failure: always
