language: cpp

before_script:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then lsb_release -a; uname -a; sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ utopic universe multiverse" && sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ utopic-updates universe multiverse" && sudo apt-get update && apt-cache search '^g\+\+|^clang' && sudo apt-get install -y bash coreutils ncurses-bin clang-3.4; fi

script: bash -c 'pwd && ls && USE_CC=clang++-3.4 ./validate.sh'

branches:
  only:
    - dev

notifications:
  email:
    on_success: change
    on_failure: always

os:
  - linux
