language: cpp

os:
  - linux

compiler:
  - clang

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - bash
    - coreutils
    - g++-4.8
    - g++-4.9
    - g++-5
    - clang-3.4

before_install:
  - echo $LANG
  - echo $LC_ALL
  - lsb_release -a
  - uname -a

install:
  - apt-cache search '^g\+\+|^clang'

before_script:
  - echo $LANG
  - echo $LC_ALL
  - lsb_release -a
  - uname -a
  - apt-cache search '^g\+\+|^clang'

script:
  - for cc in g++-4.8 g++-4.9 g++-5; do if which $cc; then $cc --version; else echo "no $cc installed, skipping validation"; fi; USE_CC=$cc NO_CLEAR=true ./validate.sh nobuild; done
  - for cc in clang++ clang++-3.4 clang++-3.5 clang++-3.6 clang++-3.7; do if which $cc; then $cc --version; else echo "no $cc installed, skipping validation"; fi; USE_CC=$cc NO_CLEAR=true ./validate.sh; done

branches:
  only:
    - dev

notifications:
  email:
    on_success: change
    on_failure: always
