language: cpp

os:
  - linux

compiler:
  - clang

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - bash
    - coreutils
    - g++-4.8
    - g++-4.9
    - g++-5
    - clang-3.4
    - clang-3.5

before_install:
  - echo $LANG
  - echo $LC_ALL
  - lsb_release -a
  - uname -a

install:
  - apt-cache search '^g\+\+|^clang'

before_script:
  - echo $LANG
  - echo $LC_ALL
  - lsb_release -a
  - uname -a
  - apt-cache search '^g\+\+|^clang'

script:
  - ./contbuild.sh

branches:
  only:
    - dev

notifications:
  email:
    on_success: change
    on_failure: always
