language: cpp

sudo: false

matrix:
  include:
# Disabling Travis' faulty gcc 4.8
#    - os: linux
#      compiler: gcc
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test']
#          packages: ['g++-4.8']
#      env: COMPILER=g++-4.8
#
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: COMPILER=g++-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: COMPILER=g++-5

# Disabling Travis' faulty clang 3.4
#    - os: linux
#      compiler: clang
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.4' ]
#          packages: ['clang-3.4', 'libc++']
#      env: COMPILER=clang++

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages: ['clang-3.5']
      env: COMPILER=clang++-3.5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6']
      env: COMPILER=clang++-3.6

# Not yet available
#    - os: linux
#      compiler: clang
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
#          packages: ['clang-3.7']
#      env: COMPILER=clang++-3.7

# Not yet available
#    - os: linux
#      compiler: clang
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise']
#          packages: ['clang-3.8']
#      env: COMPILER=clang++-3.8

# Activate when we are allowed to use MacOS X
#    - os: osx
#      compiler: clang
#      env: COMPILER=clang++

addons:
  apt:
    packages:
    - bash
    - coreutils

before_install:
  - echo $LANG
  - echo $LC_ALL
  - lsb_release -a
  - uname -a

install:
  - apt-cache search '^g\+\+|^clang'

before_script:
  - echo $LANG
  - echo $LC_ALL
  - lsb_release -a
  - uname -a
  - apt-cache search '^g\+\+|^clang'

script:
  - ./contbuild.sh "$COMPILER"

branches:
  only:
    - master
    - dev

notifications:
  email:
    on_success: change
    on_failure: always
