language: cpp

os:
  - linux

compiler:
  - clang

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y bash coreutils g++-4.8 g++-4.9 clang-3.4

before_script:
  - echo $LANG
  - echo $LC_ALL
  - lsb_release -a
  - uname -a
  - apt-cache search '^g\+\+|^clang'

script:
  - for cc in g++ g++-4.8 g++-4.9 clang++ clang++-3.4 clang++-3.5; do if which $cc; then $cc --version; USE_CC=$cc NO_CLEAR=true ./validate.sh; else echo "no $cc installed"; fi; done

branches:
  only:
    - dev

notifications:
  email:
    on_success: change
    on_failure: always
